#!/bin/bash
# 🔍 VIPER Microservices Status Check Script
# Generated by Microservices Connectivity Validator
# Generated: 2025-08-29T16:17:51.076032

echo "🔍 VIPER Microservices Status Check"
echo "=" * 40

# Function to check service health
check_service() {
    local service_name=$1
    local url=$2
    
    echo -n "Checking $service_name... "
    
    if curl -s --connect-timeout 5 "$url" > /dev/null; then
        echo "✅ HEALTHY"
    else
        echo "❌ UNHEALTHY"
    fi
}

# Check all services
check_service "api-server" "http://localhost:8000/health"
check_service "ultra-backtester" "http://localhost:8001/health"
check_service "risk-manager" "http://localhost:8002/health"
check_service "market-data-manager" "http://localhost:8003/health"
check_service "strategy-optimizer" "http://localhost:8004/health"
check_service "exchange-connector" "http://localhost:8005/health"
check_service "monitoring-service" "http://localhost:8006/health"
check_service "live-trading-engine" "http://localhost:8007/health"
check_service "centralized-logger" "http://localhost:8008/health"
check_service "viper-scoring-service" "http://localhost:8009/health"
check_service "position-synchronizer" "http://localhost:8010/health"
check_service "unified-scanner" "http://localhost:8011/health"
check_service "signal-processor" "http://localhost:8012/health"
check_service "task-scheduler" "http://localhost:8013/health"
check_service "alert-system" "http://localhost:8014/health"
check_service "mcp-server" "http://localhost:8015/health"
check_service "github-manager" "http://localhost:8016/health"
check_service "workflow-monitor" "http://localhost:8017/health"
check_service "event-system" "http://localhost:8018/health"
check_service "data-manager" "http://localhost:8019/health"
check_service "config-manager" "http://localhost:8020/health"
check_service "credential-vault" "http://localhost:8021/health"
check_service "market-data-streamer" "http://localhost:8022/health"
check_service "order-lifecycle-manager" "http://localhost:8023/health"
check_service "trading-optimizer" "http://localhost:8024/health"

echo ""
echo "🔄 Use 'docker ps' to check Docker containers"
echo "📊 Use 'scripts/comprehensive_system_validator.py' for detailed analysis"
