#!/bin/bash
# 🚀 VIPER Microservices Startup Script
# Generated by Microservices Connectivity Validator
# Generated: 2025-08-29T16:17:51.075740

echo "🚀 Starting VIPER Microservices..."
echo "=" * 50

# Set environment variables
export PYTHONPATH="/home/runner/work/viper-/viper-:$PYTHONPATH"

# Function to start a service
start_service() {
    local service_name=$1
    local port=$2
    local service_dir="/home/runner/work/viper-/viper-/services/$service_name"
    
    if [ -d "$service_dir" ]; then
        echo "🔄 Starting $service_name on port $port..."
        cd "$service_dir"
        python main.py &
        sleep 2
    else
        echo "⚠️ Service directory not found: $service_dir"
    fi
}

# Start all services in dependency order
start_service "api-server" 8000
start_service "ultra-backtester" 8001
start_service "risk-manager" 8002
start_service "market-data-manager" 8003
start_service "strategy-optimizer" 8004
start_service "exchange-connector" 8005
start_service "monitoring-service" 8006
start_service "live-trading-engine" 8007
start_service "centralized-logger" 8008
start_service "viper-scoring-service" 8009
start_service "position-synchronizer" 8010
start_service "unified-scanner" 8011
start_service "signal-processor" 8012
start_service "task-scheduler" 8013
start_service "alert-system" 8014
start_service "mcp-server" 8015
start_service "github-manager" 8016
start_service "workflow-monitor" 8017
start_service "event-system" 8018
start_service "data-manager" 8019
start_service "config-manager" 8020
start_service "credential-vault" 8021
start_service "market-data-streamer" 8022
start_service "order-lifecycle-manager" 8023
start_service "trading-optimizer" 8024

echo "✅ All microservices startup initiated"
echo "🔍 Use 'scripts/check_services.sh' to verify status"
echo "📊 Check logs in individual service directories"

# Wait for all background processes
wait
