name: VIPER Trading System CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run syntax check
      run: |
        python -m py_compile main.py
        echo "✅ Syntax check passed"

    - name: Check for API keys in code
      run: |
        if grep -r "BITGET_API" main.py; then
          echo "❌ API keys found in code - security risk!"
          exit 1
        else
          echo "✅ No hardcoded API keys found"
        fi

    - name: Validate environment variables
      run: |
        python -c "
        import os
        from dotenv import load_dotenv
        load_dotenv()
        required_vars = ['BITGET_API_KEY', 'BITGET_API_SECRET', 'BITGET_API_PASSWORD']
        missing = [var for var in required_vars if not os.getenv(var)]
        if missing:
            print(f'⚠️  Missing environment variables: {missing}')
            print('Note: This is expected in CI - real API keys should be in .env')
        else:
            print('✅ Environment variables configured')
        "

    - name: Test imports and basic functionality
      run: |
        python -c "
        try:
            import main
            print('✅ Main module imports successfully')
            trader = main.SimpleVIPERTrader()
            print('✅ SimpleVIPERTrader class initializes')
            print(f'📊 Configured for {len(trader.all_symbols)} symbols')
            print(f'🎯 Min leverage required: {trader.min_leverage_required}x')
        except Exception as e:
            print(f'❌ Import test failed: {e}')
            exit(1)
        "

  validate-config:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Validate .env structure
      run: |
        if [ ! -f .env ]; then
          echo "❌ .env file missing"
          exit 1
        fi

        # Check for required trading parameters
        required_params=(
          "POSITION_SIZE_USDT"
          "MAX_POSITIONS"
          "TAKE_PROFIT_PCT"
          "STOP_LOSS_PCT"
          "MIN_LEVERAGE_REQUIRED"
        )

        for param in "${required_params[@]}"; do
          if ! grep -q "^${param}=" .env; then
            echo "❌ Missing required parameter: ${param}"
            exit 1
          fi
        done

        echo "✅ Configuration validation passed"

    - name: Check for sensitive data
      run: |
        if grep -r "BITGET_API_KEY\|BITGET_API_SECRET\|BITGET_API_PASSWORD" .env; then
          echo "✅ API credentials found in .env"
        else
          echo "⚠️  No API credentials found in .env"
        fi

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run security scan
      run: |
        echo "🔍 Running security scan..."

        # Check for hardcoded secrets
        if grep -r "sk-\|pk_\|secret\|password\|api_key" --exclude-dir=.git --exclude=*.log --exclude=.env main.py; then
          echo "❌ Potential hardcoded secrets found"
          exit 1
        fi

        # Check file permissions
        if [ -w main.py ]; then
          echo "✅ File permissions look good"
        fi

        echo "✅ Security scan completed"

  deploy:
    needs: [test, validate-config, security-scan]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4

    - name: Deploy notification
      run: |
        echo "🚀 VIPER Trading System Ready for Deployment"
        echo "✅ All tests passed"
        echo "✅ Configuration validated"
        echo "✅ Security scan completed"
        echo ""
        echo "📊 System Status:"
        echo "   - Single position per pair: ✅ ENABLED"
        echo "   - Leverage validation: ✅ ENABLED (34x min)"
        echo "   - Balance validation: ✅ ENABLED"
        echo "   - Risk management: ✅ ENABLED"
        echo "   - Capital stacking: 🚫 DISABLED"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy.result }}" = "success" ]; then
          echo "✅ VIPER Trading System deployment successful"
        else
          echo "❌ VIPER Trading System deployment failed"
          exit 1
        fi
